Repository opencollective/opencollective-frontend, pull requests merged in 2018-10, with the labels that each got.

#854 Use internal navigation for links in footer
  src/components/Footer.js
  src/pages/__tests__/__snapshots__/search.test.js.snap
Labels: performance

#836 Load external Javascript libraries on demand
  cypress/integration/1-collective.test.js
  cypress/integration/3-expenses.page.test.js
  package-lock.json
  package.json
  src/components/InputTypeCreditCard.js
  src/components/Map.js
  src/components/OrderForm.js
  src/lib/google-maps.js
  src/lib/paypal.js
  src/lib/stripe.js
  src/lib/utils.js
  src/next.config.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/createCollective.js
  src/pages/createEvent.js
  src/pages/editCollective.js
  src/pages/editEvent.js
  src/pages/event.js
Labels: performance

#850 Load css with next-css
  package-lock.json
  package.json
  src/components/HTMLEditor.js
  src/components/InputField.js
  src/components/InputTypeTags.js
  src/components/MarkdownEditor.js
  src/index.css
  src/next.config.js
  src/styles/react-datetime.css
  src/styles/react-tags.css
Labels: performance

#871 Bundle bootstrap and font-awesome
  package-lock.json
  package.json
  src/components/Header.js
  src/next.config.js
  src/pages/_app.js
Labels: performance

#905 Fix download invoices
  src/apps/expenses/components/DownloadInvoicesPopOver.js
  src/server/routes.js
Labels: bug

#896 Handle search submit client side
  src/components/SearchForm.js
  src/pages/__tests__/__snapshots__/search.test.js.snap
Labels: performance

#903 Handle event navigation client side
  src/components/Collective.js
  src/components/Event.js
  src/components/EventsWithData.js
  src/components/Logo.js
  src/components/MenuBar.js
  src/pages/events-iframe.js
Labels: performance

#913 completePledge: initial form submission
  Dockerfile
  src/components/ButtonGroup.js
  src/components/MenuBar.js
  src/components/OrderForm.js
  src/components/StyledInput.js
  src/graphql/schema.graphql
  src/pages/claimCollective.js
  src/pages/completePledge.js
  src/pages/createPledge.js
  src/server/pages.js
Labels: Request for Comments
