Repository opencollective/opencollective-frontend, pull requests merged in 2020-11, with the labels that each got.

#5319 Collective Navigation v2: move Collective page features to new sections
  components/collective-page/_constants.js
  components/collective-page/index.js
  components/collective-page/sections/Budget.js
  components/collective-page/sections/Connect.js
  components/collective-page/sections/Contribute.js
  components/collective-page/sections/Goals.js
  components/conversations/graphql.js
  env.js
  lang/ca.json
  lang/cs.json
  lang/de.json
  lang/en.json
  lang/es.json
  lang/fr.json
  lang/it.json
  lang/ja.json
  lang/ko.json
  lang/nl.json
  lang/pt.json
  lang/ru.json
  lang/zh.json
  lib/__tests__/collective-sections.test.js
  lib/collective-sections.js
  lib/collective.lib.js
  lib/graphql/schemaV2.graphql
  lib/i18n-collective-page-section.js
  next.config.js
  pages/_document.js
Labels: needs-squashing

#5374 Fix bug when expense has no items and it is not a draft
  components/expenses/ExpenseSummary.js
Labels: bug

#5395 Fix overflowing user email address
  components/TopBarProfileMenu.js
Labels: needs-squashing

#5108 refactor : remove moment in favor of dayjs
  components/CreateEvent.js
  components/CreateVirtualCardsForm.js
  components/DateTime.js
  components/Moment.js
  components/TimezonePicker.js
  components/VirtualCardDetails.js
  components/collective-page/hero/HeroEventDetails.js
  components/expenses/DownloadInvoicesPopOver.js
  components/expenses/TransactionsExportPopoverAndButton.js
  components/transactions/TransactionsDownloadCSV.js
  components/transactions/TransactionsDownloadInvoices.js
  lib/constants/timezones.js
  lib/dayjs.js
  lib/payment_method_label.js
  lib/withLoggedInUser.js
  package-lock.json
  package.json
Labels: PR: review-requested
